"""add_invite_code_is_public_member_status

Revision ID: 1be05745ead6
Revises: b721c01b567f
Create Date: 2026-03-02 20:19:49.798291

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1be05745ead6'
down_revision: str | Sequence[str] | None = 'b721c01b567f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league_members', sa.Column('status', sa.String(length=20), server_default='approved', nullable=False))
    op.add_column('leagues', sa.Column('invite_code', sa.String(length=50), server_default=sa.text("replace(gen_random_uuid()::text, '-', '')"), nullable=False))
    op.add_column('leagues', sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_leagues_invite_code'), 'leagues', ['invite_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leagues_invite_code'), table_name='leagues')
    op.drop_column('leagues', 'is_public')
    op.drop_column('leagues', 'invite_code')
    op.drop_column('league_members', 'status')
    # ### end Alembic commands ###
