"""
Leagues router — /leagues/*

Endpoints:
  POST   /leagues                                          Create a new league
  POST   /leagues/join/{invite_code}                       Submit a join request via invite link
  GET    /leagues/{league_id}                              Get league details (members only)
  PATCH  /leagues/{league_id}                              Update league name/penalty (manager only)
  DELETE /leagues/{league_id}                              Delete a league and all its data (manager only)
  GET    /leagues/{league_id}/members                      List approved members
  PATCH  /leagues/{league_id}/members/{user_id}/role       Change a member's role (manager only)
  DELETE /leagues/{league_id}/members/me                   Leave a league (any approved member)
  DELETE /leagues/{league_id}/members/{user_id}            Remove a member (manager only)
  GET    /leagues/{league_id}/requests                     List pending join requests (manager only)
  POST   /leagues/{league_id}/requests/{user_id}/approve   Approve a join request (manager only)
  DELETE /leagues/{league_id}/requests/{user_id}           Deny/delete a join request (manager only)
  GET    /leagues/{league_id}/tournaments                  List league's selected tournaments
  PUT    /leagues/{league_id}/tournaments                  Replace league's tournament schedule (manager only)
"""

import datetime
import logging
import math
import uuid

log = logging.getLogger(__name__)

LEAGUE_MEMBER_CAP = 500
LEAGUE_PENDING_CAP = LEAGUE_MEMBER_CAP // 5  # 100
USER_LEAGUE_CAP = 5  # Max approved leagues a single user may belong to (created + joined combined)

from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel, field_validator
from sqlalchemy.orm import Session, joinedload

from app.limiter import limiter
from app.config import settings

from app.database import get_db
from app.dependencies import get_current_user, get_league_or_404, require_league_manager, require_league_member
from app.models import (
    League,
    LeagueMember,
    LeagueMemberRole,
    LeagueMemberStatus,
    LeagueTournament,
    Pick,
    PlayoffConfig,
    PlayoffDraftPreference,
    PlayoffPod,
    PlayoffPodMember,
    PlayoffPick,
    PlayoffRound,
    Season,
    Tournament,
    User,
)
from app.schemas.league import LeagueCreate, LeagueMemberOut, LeagueOut, LeagueUpdate, LeagueJoinPreview, LeagueRequestOut, RoleUpdate
from app.schemas.tournament import LeagueTournamentOut, TournamentOut
from app.models.tournament import TournamentStatus
from app.services.picks import all_r1_teed_off as _all_r1_teed_off
from app.services.scraper import score_picks

router = APIRouter(prefix="/leagues", tags=["leagues"])

# ---------------------------------------------------------------------------
# League creation
# ---------------------------------------------------------------------------


@router.post("", response_model=LeagueOut, status_code=201)
@limiter.limit("5/hour")
def create_league(
    request: Request,
    body: LeagueCreate,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Create a new league. The creator is automatically made an approved admin.
    An active season for the current calendar year is created. All leagues are
    private by default — joining requires an invite link and manager approval.
    """
    # Guard: league creation may be restricted to platform admins only.
    if settings.LEAGUE_CREATION_RESTRICTED and not current_user.is_platform_admin:
        raise HTTPException(
            status_code=403,
            detail="League creation is not available yet. Stay tuned!",
        )

    # Guard: per-user league cap — checked before any DB write so nothing is rolled back.
    user_league_count = db.query(LeagueMember).filter_by(
        user_id=current_user.id,
        status=LeagueMemberStatus.APPROVED.value,
    ).count()
    if user_league_count >= USER_LEAGUE_CAP:
        raise HTTPException(
            status_code=400,
            detail=f"You have reached the maximum of {USER_LEAGUE_CAP} leagues. Leave a league before creating another.",
        )

    league = League(
        name=body.name,
        no_pick_penalty=body.no_pick_penalty,
        created_by=current_user.id,
        # is_public defaults to False; invite_code auto-generated by model default
    )
    db.add(league)
    db.flush()  # Get the league ID before adding related objects.

    # Auto-add creator as an approved league manager — no approval step needed for the founder.
    membership = LeagueMember(
        league_id=league.id,
        user_id=current_user.id,
        role=LeagueMemberRole.MANAGER.value,
        status=LeagueMemberStatus.APPROVED.value,
    )
    db.add(membership)

    # Create the initial season for the current year.
    season = Season(league_id=league.id, year=datetime.date.today().year, is_active=True)
    db.add(season)

    db.commit()
    db.refresh(league)
    return league


# ---------------------------------------------------------------------------
# Invite-code join
# ---------------------------------------------------------------------------


@router.get("/join/{invite_code}", response_model=LeagueJoinPreview)
def preview_join(
    invite_code: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Preview a league before submitting a join request.

    Returns the league name, member count, and the current user's
    relationship to it (None = no request, "pending" = waiting, "approved" = member).
    Does not create or modify any records.
    """
    league = db.query(League).filter_by(invite_code=invite_code).first()
    if not league:
        raise HTTPException(status_code=404, detail="Invalid invite link — league not found")

    member_count = db.query(LeagueMember).filter_by(
        league_id=league.id, status=LeagueMemberStatus.APPROVED.value
    ).count()

    existing = db.query(LeagueMember).filter_by(
        league_id=league.id, user_id=current_user.id
    ).first()

    return LeagueJoinPreview(
        league_id=league.id,
        name=league.name,
        member_count=member_count,
        user_status=existing.status if existing else None,
    )


@router.get("/my-requests", response_model=list[LeagueRequestOut])
def my_join_requests(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Return the current user's pending join requests across all leagues."""
    rows = (
        db.query(LeagueMember, League)
        .join(League, LeagueMember.league_id == League.id)
        .filter(
            LeagueMember.user_id == current_user.id,
            LeagueMember.status == LeagueMemberStatus.PENDING.value,
        )
        .all()
    )
    return [
        LeagueRequestOut(
            league_id=league.id,
            league_name=league.name,
            requested_at=member.joined_at,
        )
        for member, league in rows
    ]


@router.post("/join/{invite_code}", response_model=LeagueMemberOut, status_code=201)
@limiter.limit("10/hour")
def request_to_join(
    request: Request,
    invite_code: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Submit a join request using a league's invite code.

    Private leagues (default): creates a "pending" membership. A league manager must
    approve before the user has access to the league.

    Public leagues (future): auto-approves and returns an "approved" membership.

    The invite code is shared by league managers; it is the only way to request
    membership. Admins can find their invite link in the Admin panel.

    Rate-limited to 10 requests per IP per hour to prevent invite-code brute-forcing.
    Max 50 pending requests per league. Max 500 approved members per league.
    """
    league = db.query(League).filter_by(invite_code=invite_code).first()
    if not league:
        raise HTTPException(status_code=404, detail="Invalid invite link — league not found")

    existing = db.query(LeagueMember).filter_by(
        league_id=league.id, user_id=current_user.id
    ).first()
    if existing:
        if existing.status == LeagueMemberStatus.APPROVED.value:
            raise HTTPException(status_code=409, detail="You are already a member of this league")
        raise HTTPException(status_code=409, detail="You already have a pending join request for this league")

    # Guard: per-user league cap — block the request now so the user isn't waiting for
    # an approval that can never succeed.
    user_league_count = db.query(LeagueMember).filter_by(
        user_id=current_user.id,
        status=LeagueMemberStatus.APPROVED.value,
    ).count()
    if user_league_count >= USER_LEAGUE_CAP:
        raise HTTPException(
            status_code=400,
            detail=f"You have reached the maximum of {USER_LEAGUE_CAP} leagues. Leave a league before joining another.",
        )

    # Guard: too many pending requests already in the queue for this league.
    pending_count = db.query(LeagueMember).filter_by(
        league_id=league.id, status=LeagueMemberStatus.PENDING.value
    ).count()
    if pending_count >= LEAGUE_PENDING_CAP:
        raise HTTPException(
            status_code=400,
            detail="This league has too many pending join requests. Please try again later or contact the league manager.",
        )

    # Public leagues skip the approval step — check member cap before auto-approving.
    if league.is_public:
        approved_count = db.query(LeagueMember).filter_by(
            league_id=league.id, status=LeagueMemberStatus.APPROVED.value
        ).count()
        if approved_count >= LEAGUE_MEMBER_CAP:
            raise HTTPException(
                status_code=400,
                detail=f"This league has reached its maximum member limit of {LEAGUE_MEMBER_CAP}.",
            )

    initial_status = (
        LeagueMemberStatus.APPROVED.value
        if league.is_public
        else LeagueMemberStatus.PENDING.value
    )

    membership = LeagueMember(
        league_id=league.id,
        user_id=current_user.id,
        role=LeagueMemberRole.MEMBER.value,
        status=initial_status,
    )
    db.add(membership)
    db.commit()
    db.refresh(membership)
    membership.user = current_user
    return membership


# ---------------------------------------------------------------------------
# League detail & membership management
# ---------------------------------------------------------------------------


@router.get("/{league_id}", response_model=LeagueOut)
def get_league(
    league_and_member: tuple[League, LeagueMember] = Depends(require_league_member),
):
    """Return league details including invite_code. Requires approved membership."""
    league, _ = league_and_member
    return league


@router.patch("/{league_id}", response_model=LeagueOut)
def update_league(
    body: LeagueUpdate,
    league_and_manager: tuple[League, LeagueMember] = Depends(require_league_manager),
    db: Session = Depends(get_db),
):
    """Update league name or no_pick_penalty. Requires league manager."""
    league, _ = league_and_manager
    if body.name is not None:
        league.name = body.name
    if body.no_pick_penalty is not None:
        league.no_pick_penalty = body.no_pick_penalty
    db.commit()
    db.refresh(league)
    return league


@router.delete("/{league_id}", status_code=204)
def delete_league(
    league_and_manager: tuple[League, LeagueMember] = Depends(require_league_manager),
    db: Session = Depends(get_db),
):
    """
    Permanently delete a league and all associated data. Requires league manager. Cannot be undone.

    Uses explicit bulk DELETEs in FK-safe order (leaf tables first). Avoids relying on ORM
    cascade because PlayoffDraftPreference has two delete-orphan parents (pod + pod_member),
    which SQLAlchemy can reject. Subqueries walk the playoff hierarchy:
      league → playoff_configs → playoff_rounds → playoff_pods
                                                  ↳ playoff_pod_members → playoff_draft_preferences
                                                  ↳ playoff_picks
                                                  ↳ playoff_draft_preferences
    Regular tables: picks → seasons → league_members → league_tournaments → league.
    """
    league, manager = league_and_manager
    log.warning(
        "League deleted: league_id=%s name=%r by user_id=%s",
        league.id, league.name, manager.user_id,
    )

    # Build subquery chains for playoff tables (no direct league_id FK below playoff_configs).
    config_ids = db.query(PlayoffConfig.id).filter(PlayoffConfig.league_id == league.id).subquery()
    round_ids  = db.query(PlayoffRound.id).filter(PlayoffRound.playoff_config_id.in_(config_ids)).subquery()
    pod_ids    = db.query(PlayoffPod.id).filter(PlayoffPod.playoff_round_id.in_(round_ids)).subquery()

    # Leaf playoff tables first (both FKs point at pods/pod_members — delete before those).
    db.query(PlayoffDraftPreference).filter(PlayoffDraftPreference.pod_id.in_(pod_ids)).delete(synchronize_session=False)
    db.query(PlayoffPick).filter(PlayoffPick.pod_id.in_(pod_ids)).delete(synchronize_session=False)
    # Pod members reference pods.
    db.query(PlayoffPodMember).filter(PlayoffPodMember.pod_id.in_(pod_ids)).delete(synchronize_session=False)
    # Pods reference rounds; rounds reference configs.
    db.query(PlayoffPod).filter(PlayoffPod.playoff_round_id.in_(round_ids)).delete(synchronize_session=False)
    db.query(PlayoffRound).filter(PlayoffRound.playoff_config_id.in_(config_ids)).delete(synchronize_session=False)
    db.query(PlayoffConfig).filter(PlayoffConfig.league_id == league.id).delete(synchronize_session=False)

    # Regular-season picks reference league + season.
    db.query(Pick).filter(Pick.league_id == league.id).delete(synchronize_session=False)
    # Seasons reference league.
    db.query(Season).filter(Season.league_id == league.id).delete(synchronize_session=False)
    # Join/membership tables reference league.
    db.query(LeagueMember).filter(LeagueMember.league_id == league.id).delete(synchronize_session=False)
    db.query(LeagueTournament).filter(LeagueTournament.league_id == league.id).delete(synchronize_session=False)

    db.delete(league)
    db.commit()


@router.get("/{league_id}/members", response_model=list[LeagueMemberOut])
def list_members(
    league_and_member: tuple[League, LeagueMember] = Depends(require_league_member),
    db: Session = Depends(get_db),
):
    """List approved members of a league. Requires membership."""
    league, _ = league_and_member
    return (
        db.query(LeagueMember)
        .filter_by(league_id=league.id, status=LeagueMemberStatus.APPROVED.value)
        .options(joinedload(LeagueMember.user))
        .all()
    )


@router.patch("/{league_id}/members/{user_id}/role", response_model=LeagueMemberOut)
def update_member_role(
    user_id: uuid.UUID,
    body: RoleUpdate,
    league_and_manager: tuple[League, LeagueMember] = Depends(require_league_manager),
    db: Session = Depends(get_db),
):
    """Change an approved member's role. Requires league manager."""
    league, _ = league_and_manager

    if body.role not in (LeagueMemberRole.MANAGER.value, LeagueMemberRole.MEMBER.value):
        raise HTTPException(status_code=400, detail="Role must be 'manager' or 'member'")

    membership = (
        db.query(LeagueMember)
        .filter_by(league_id=league.id, user_id=user_id, status=LeagueMemberStatus.APPROVED.value)
        .options(joinedload(LeagueMember.user))
        .first()
    )
    if not membership:
        raise HTTPException(status_code=404, detail="Member not found")

    membership.role = body.role
    db.commit()
    db.refresh(membership)
    return membership


# ---------------------------------------------------------------------------
# Member removal helpers
# ---------------------------------------------------------------------------


def _remove_member_picks_and_playoff(
    db: Session, league: League, user_id: uuid.UUID
) -> None:
    """
    Clean up season data for a member leaving or being removed from a league.

    Handles three cases from the rules:
      1. Regular season: deletes all Pick records for the current season.
      2. Playoffs, member NOT in playoffs: same — picks deleted, no bracket impact.
      3. Playoffs, member IS in playoffs: the pod slot is preserved (bracket
         structure is never reshuffled). Picks and preference lists are deleted
         so all their slots score as no-picks. The PlayoffPodMember row is kept
         but marked is_eliminated=True so the vacant slot can never win the pod,
         regardless of how other members score.

    Only non-completed playoff rounds are affected. Rounds that have already been
    scored and advanced are left entirely intact — prior-round picks, scores, and
    winner records are permanent history and must not change.

    Called from both leave_league() and remove_member() so both paths are
    identical in their cleanup behavior.
    """
    season = db.query(Season).filter_by(league_id=league.id, is_active=True).first()
    if not season:
        return  # No active season — nothing to clean up.

    # 1. Delete all regular-season picks for this user in this league/season.
    db.query(Pick).filter_by(
        league_id=league.id,
        user_id=user_id,
        season_id=season.id,
    ).delete()

    # 2. Vacate playoff pod slots for this season (if any).
    #    A member may appear in multiple pods (one per round they reached).
    #    We keep the PlayoffPodMember row so the bracket is unchanged, but
    #    clear picks/preferences and mark the slot ineligible to win.
    #
    #    Only non-completed rounds are touched. Completed rounds (already scored
    #    and advanced) are left entirely intact — picks, scores, and winner
    #    records from prior rounds are permanent history.
    config = db.query(PlayoffConfig).filter_by(
        league_id=league.id, season_id=season.id
    ).first()
    if config:
        pod_members = (
            db.query(PlayoffPodMember)
            .join(PlayoffPod, PlayoffPodMember.pod_id == PlayoffPod.id)
            .join(PlayoffRound, PlayoffPod.playoff_round_id == PlayoffRound.id)
            .filter(
                PlayoffRound.playoff_config_id == config.id,
                PlayoffPodMember.user_id == user_id,
                PlayoffRound.status != "completed",
            )
            .all()
        )
        for pm in pod_members:
            # Delete resolved picks (no ORM cascade from pod_member → picks).
            db.query(PlayoffPick).filter_by(pod_member_id=pm.id).delete()
            # Delete submitted preferences (also no cascade, explicit delete).
            db.query(PlayoffDraftPreference).filter_by(pod_member_id=pm.id).delete()
            # Mark the slot ineligible — _determine_pod_winner skips is_eliminated=True.
            pm.is_eliminated = True

    # Auto-shrink playoff bracket size when the regular season has not yet ended.
    # Once the last regular season tournament completes, the schedule (and bracket
    # size) is locked — departing members' slots stay open as a bye instead.
    #
    # We reuse the same schedule-lock condition used in the PUT /tournaments
    # endpoint: find the last non-playoff tournament for this league and check
    # whether it is already completed.
    if config:
        _playoff_ids = _playoff_tournament_ids_for_league(league.id, db)
        _rsq = (
            db.query(Tournament)
            .join(LeagueTournament, LeagueTournament.tournament_id == Tournament.id)
            .filter(LeagueTournament.league_id == league.id)
        )
        if _playoff_ids:
            _rsq = _rsq.filter(Tournament.id.notin_(_playoff_ids))
        _last_rs = _rsq.order_by(Tournament.start_date.desc()).first()
        _schedule_locked = bool(_last_rs and _last_rs.status == TournamentStatus.COMPLETED.value)

        if not _schedule_locked:
            # Count remaining approved members, excluding the one who is leaving.
            remaining = (
                db.query(LeagueMember)
                .filter(
                    LeagueMember.league_id == league.id,
                    LeagueMember.status == LeagueMemberStatus.APPROVED.value,
                    LeagueMember.user_id != user_id,
                )
                .count()
            )
            if config.playoff_size > 0 and remaining < config.playoff_size:
                # Reduce to the largest valid bracket size (power of 2) that fits.
                valid_sizes = [2, 4, 8, 16, 32]
                new_size = max((s for s in valid_sizes if s <= remaining), default=0)
                config.playoff_size = new_size

    db.flush()


@router.delete("/{league_id}/members/me", status_code=204)
def leave_league(
    league_and_member: tuple[League, LeagueMember] = Depends(require_league_member),
    db: Session = Depends(get_db),
):
    """Allow any approved member to leave a league voluntarily."""
    league, membership = league_and_member
    log.info("Member left: league_id=%s user_id=%s", league.id, membership.user_id)
    _remove_member_picks_and_playoff(db, league, membership.user_id)
    db.delete(membership)
    db.commit()


@router.delete("/{league_id}/members/{user_id}", status_code=204)
def remove_member(
    user_id: uuid.UUID,
    league_and_manager: tuple[League, LeagueMember] = Depends(require_league_manager),
    db: Session = Depends(get_db),
):
    """Remove an approved member from a league. Requires league manager."""
    league, manager_membership = league_and_manager
    log.info(
        "Member removed: league_id=%s target_user_id=%s by manager_user_id=%s",
        league.id, user_id, manager_membership.user_id,
    )

    if user_id == manager_membership.user_id:
        raise HTTPException(status_code=400, detail="You cannot remove yourself from the league")

    membership = db.query(LeagueMember).filter_by(
        league_id=league.id, user_id=user_id, status=LeagueMemberStatus.APPROVED.value
    ).first()
    if not membership:
        raise HTTPException(status_code=404, detail="Member not found")

    _remove_member_picks_and_playoff(db, league, user_id)
    db.delete(membership)
    db.commit()


# ---------------------------------------------------------------------------
# Join request management (manager only)
# ---------------------------------------------------------------------------


@router.get("/{league_id}/requests", response_model=list[LeagueMemberOut])
def list_join_requests(
    league_and_manager: tuple[League, LeagueMember] = Depends(require_league_manager),
    db: Session = Depends(get_db),
):
    """List pending join requests. Requires league manager."""
    league, _ = league_and_manager
    return (
        db.query(LeagueMember)
        .filter_by(league_id=league.id, status=LeagueMemberStatus.PENDING.value)
        .options(joinedload(LeagueMember.user))
        .all()
    )


@router.post("/{league_id}/requests/{user_id}/approve", response_model=LeagueMemberOut)
def approve_join_request(
    user_id: uuid.UUID,
    league_and_manager: tuple[League, LeagueMember] = Depends(require_league_manager),
    db: Session = Depends(get_db),
):
    """Approve a pending join request. Requires league manager."""
    league, _ = league_and_manager

    membership = (
        db.query(LeagueMember)
        .filter_by(league_id=league.id, user_id=user_id, status=LeagueMemberStatus.PENDING.value)
        .options(joinedload(LeagueMember.user))
        .first()
    )
    if not membership:
        raise HTTPException(status_code=404, detail="Pending request not found")

    # Guard: league member cap — checked here so admins can't accidentally exceed it
    # by approving multiple pending requests when the league is nearly full.
    approved_count = db.query(LeagueMember).filter_by(
        league_id=league.id, status=LeagueMemberStatus.APPROVED.value
    ).count()
    if approved_count >= LEAGUE_MEMBER_CAP:
        raise HTTPException(
            status_code=400,
            detail=f"This league has reached its maximum member limit of {LEAGUE_MEMBER_CAP}. Remove a member before approving new ones.",
        )

    # Guard: per-user league cap — the requestor may have joined other leagues since
    # this request was submitted. Prevents a race condition where a user submits multiple
    # pending requests and gets approved into more than USER_LEAGUE_CAP leagues.
    user_league_count = db.query(LeagueMember).filter_by(
        user_id=user_id,
        status=LeagueMemberStatus.APPROVED.value,
    ).count()
    if user_league_count >= USER_LEAGUE_CAP:
        raise HTTPException(
            status_code=400,
            detail=f"Cannot approve: this member is already in {USER_LEAGUE_CAP} leagues (the maximum). They must leave a league first.",
        )

    membership.status = LeagueMemberStatus.APPROVED.value
    db.commit()
    db.refresh(membership)
    return membership


@router.delete("/{league_id}/requests/me", status_code=204)
def cancel_my_join_request(
    league: League = Depends(get_league_or_404),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Cancel the current user's own pending join request."""
    membership = db.query(LeagueMember).filter_by(
        league_id=league.id,
        user_id=current_user.id,
        status=LeagueMemberStatus.PENDING.value,
    ).first()
    if not membership:
        raise HTTPException(status_code=404, detail="No pending request found")

    db.delete(membership)
    db.commit()


@router.delete("/{league_id}/requests/{user_id}", status_code=204)
def deny_join_request(
    user_id: uuid.UUID,
    league_and_manager: tuple[League, LeagueMember] = Depends(require_league_manager),
    db: Session = Depends(get_db),
):
    """
    Deny and delete a pending join request. Requires league manager.
    Denied requests are deleted rather than stored to keep the table clean
    and allow the user to request again later if needed.
    """
    league, _ = league_and_manager

    membership = db.query(LeagueMember).filter_by(
        league_id=league.id, user_id=user_id, status=LeagueMemberStatus.PENDING.value
    ).first()
    if not membership:
        raise HTTPException(status_code=404, detail="Pending request not found")

    db.delete(membership)
    db.commit()


# ---------------------------------------------------------------------------
# Tournament schedule
# ---------------------------------------------------------------------------


def _playoff_tournament_ids_for_league(league_id: uuid.UUID, db: Session) -> frozenset[uuid.UUID]:
    """Return the set of tournament IDs that are playoff rounds for this league.

    Two sources are combined so the result is correct at every stage of the
    playoff lifecycle:

    1. PlayoffRound.tournament_id records — authoritative once the admin opens
       each round (via POST /playoff/rounds/{id}/open). These are only populated
       after the bracket has been initialised.

    2. Computed from PlayoffConfig: the last N scheduled league tournaments
       (excluding the globally-next upcoming, which is the current pick week)
       where N = required rounds for the bracket size. This handles the period
       before any PlayoffRound records exist and serves as a fallback.

    A tournament is marked is_playoff_round=True if it appears in either source.
    Mirrors the savedPlayoffRoundMap logic in the frontend ManageLeague component.
    """
    ids: set[uuid.UUID] = set()

    # ── Source 1: explicit PlayoffRound assignments ──────────────────────────
    explicit = (
        db.query(PlayoffRound.tournament_id)
        .join(PlayoffConfig, PlayoffRound.playoff_config_id == PlayoffConfig.id)
        .filter(
            PlayoffConfig.league_id == league_id,
            PlayoffRound.tournament_id.isnot(None),
        )
        .all()
    )
    ids.update(row.tournament_id for row in explicit)

    # ── Source 2: computed from playoff config ───────────────────────────────
    config = (
        db.query(PlayoffConfig)
        .filter(PlayoffConfig.league_id == league_id)
        .first()
    )
    if config and config.playoff_size >= 2:
        # Mirror _required_rounds() from playoff.py — log2 of bracket size.
        required = 4 if config.playoff_size == 32 else int(math.log2(config.playoff_size))

        # Exclude the globally-next upcoming tournament (reserved for the current
        # pick week) only when no league tournament is currently in progress.
        # While in progress, the next tournament's pick window hasn't opened yet,
        # so it remains eligible as a playoff round.
        has_in_progress = db.query(
            db.query(LeagueTournament)
            .filter_by(league_id=league_id)
            .join(LeagueTournament.tournament)
            .filter(Tournament.status == TournamentStatus.IN_PROGRESS.value)
            .exists()
        ).scalar()

        next_upcoming_id = None
        if not has_in_progress:
            next_upcoming = (
                db.query(Tournament)
                .filter(Tournament.status == TournamentStatus.SCHEDULED.value)
                .order_by(Tournament.start_date.asc())
                .first()
            )
            next_upcoming_id = next_upcoming.id if next_upcoming else None

        candidates_q = (
            db.query(LeagueTournament)
            .filter_by(league_id=league_id)
            .join(LeagueTournament.tournament)
            .filter(Tournament.status == TournamentStatus.SCHEDULED.value)
        )
        if next_upcoming_id is not None:
            candidates_q = candidates_q.filter(Tournament.id != next_upcoming_id)

        # Last N by start_date ascending = the playoff rounds.
        rows = candidates_q.order_by(Tournament.start_date.asc()).all()
        for row in rows[-required:]:
            ids.add(row.tournament.id)

    return frozenset(ids)


def _build_league_tournament_out(
    row: LeagueTournament,
    db: Session,
    playoff_ids: frozenset[uuid.UUID] = frozenset(),
) -> LeagueTournamentOut:
    """Build a LeagueTournamentOut from a LeagueTournament row, resolving effective_multiplier.

    all_r1_teed_off is only computed for in-progress tournaments (checking the DB
    for the last Round 1 tee time). For scheduled or completed tournaments it is
    always False — the value is irrelevant outside the in-progress window.

    is_playoff_round is True when the tournament is assigned to a PlayoffRound for
    this league. Pass playoff_ids from _playoff_tournament_ids_for_league() so the
    check is O(1) without an extra DB hit per row.
    """
    t = row.tournament
    effective = row.multiplier if row.multiplier is not None else t.multiplier
    in_progress = t.status == TournamentStatus.IN_PROGRESS.value
    return LeagueTournamentOut(
        id=t.id,
        pga_tour_id=t.pga_tour_id,
        name=t.name,
        start_date=t.start_date,
        end_date=t.end_date,
        multiplier=t.multiplier,
        purse_usd=t.purse_usd,
        status=t.status,
        is_team_event=t.is_team_event,
        effective_multiplier=effective,
        all_r1_teed_off=_all_r1_teed_off(db, t.id) if in_progress else False,
        is_playoff_round=t.id in playoff_ids,
    )


@router.get("/{league_id}/tournaments", response_model=list[LeagueTournamentOut])
def get_league_tournaments(
    league_and_member: tuple[League, LeagueMember] = Depends(require_league_member),
    db: Session = Depends(get_db),
):
    """
    Return the tournaments selected for this league's schedule, sorted by
    start_date ascending. Each tournament includes effective_multiplier, which
    resolves to the league's per-tournament override or the global default.
    Returns [] if the admin hasn't configured the schedule yet.
    """
    league, _ = league_and_member
    rows = (
        db.query(LeagueTournament)
        .filter_by(league_id=league.id)
        .join(LeagueTournament.tournament)
        .order_by(Tournament.start_date.asc())
        .all()
    )
    playoff_ids = _playoff_tournament_ids_for_league(league.id, db)
    return [_build_league_tournament_out(row, db, playoff_ids) for row in rows]


class TournamentScheduleItem(BaseModel):
    tournament_id: uuid.UUID
    multiplier: float | None = None  # None = inherit from tournament.multiplier

    @field_validator("multiplier")
    @classmethod
    def multiplier_must_be_valid(cls, v: float | None) -> float | None:
        if v is not None and v not in (1.0, 1.5, 2.0):
            raise ValueError("multiplier must be 1.0, 1.5, or 2.0")
        return v


class TournamentScheduleUpdate(BaseModel):
    tournaments: list[TournamentScheduleItem]


@router.put("/{league_id}/tournaments", response_model=list[LeagueTournamentOut])
def update_league_tournaments(
    body: TournamentScheduleUpdate,
    league_and_manager: tuple[League, LeagueMember] = Depends(require_league_manager),
    db: Session = Depends(get_db),
):
    """
    Atomically replace the league's tournament schedule.

    Accepts a full list of {tournament_id, multiplier} objects.
    Multiplier may be null to inherit the tournament's global default.

    Validation:
    - Schedule is locked once the last regular season tournament is completed
      — no further changes are allowed.
    - At most one tournament per ISO calendar week (same week = same ISO year+week).
    - If the league has a pending playoff config, the new schedule must include
      enough future (scheduled) tournaments to fill the bracket. Playoff rounds
      are automatically the last N scheduled tournaments — no explicit flag needed.

    All completed tournaments are re-scored after save.

    Requires league manager.
    """
    league, _ = league_and_manager

    tournament_ids = [item.tournament_id for item in body.tournaments]

    # Verify all requested tournament IDs actually exist; build lookup dict.
    tournament_map: dict = {}
    if tournament_ids:
        rows = db.query(Tournament).filter(Tournament.id.in_(tournament_ids)).all()
        if len(rows) != len(tournament_ids):
            raise HTTPException(status_code=422, detail="One or more tournament IDs not found")
        tournament_map = {t.id: t for t in rows}

    # Rule: all tournaments must fall within the active season's calendar year.
    active_season = db.query(Season).filter_by(league_id=league.id, is_active=True).first()
    if active_season:
        for t in tournament_map.values():
            if t.start_date.year != active_season.year:
                raise HTTPException(
                    status_code=422,
                    detail=(
                        f"{t.name!r} starts in {t.start_date.year}, but the active season is "
                        f"{active_season.year} — only tournaments from that year can be scheduled"
                    ),
                )

    # Rule: schedule locks once the last regular season tournament is completed.
    # Playoff tournaments are excluded — they can still be managed after the regular season ends.
    playoff_ids = _playoff_tournament_ids_for_league(league.id, db)
    q = (
        db.query(Tournament)
        .join(LeagueTournament, LeagueTournament.tournament_id == Tournament.id)
        .filter(LeagueTournament.league_id == league.id)
    )
    if playoff_ids:
        q = q.filter(Tournament.id.notin_(playoff_ids))
    last_regular_season = q.order_by(Tournament.start_date.desc()).first()
    if last_regular_season and last_regular_season.status == TournamentStatus.COMPLETED.value:
        raise HTTPException(
            status_code=422,
            detail="Schedule is locked — the final regular season tournament has already completed",
        )

    # Rule: only one tournament per ISO calendar week.
    week_map: dict[tuple[int, int], str] = {}
    for item in body.tournaments:
        t = tournament_map.get(item.tournament_id)
        if t:
            iso = t.start_date.isocalendar()
            key = (iso.year, iso.week)
            if key in week_map:
                raise HTTPException(
                    status_code=422,
                    detail=(
                        f"Schedule cannot include more than one tournament per calendar week "
                        f"({week_map[key]!r} and {t.name!r} are in the same week)"
                    ),
                )
            week_map[key] = t.name

    # If a pending playoff config exists, ensure the new schedule has enough
    # eligible future tournaments (scheduled, not the current week's tournament).
    playoff_config = (
        db.query(PlayoffConfig)
        .join(Season, PlayoffConfig.season_id == Season.id)
        .filter(PlayoffConfig.league_id == league.id, Season.is_active.is_(True))
        .first()
    )
    if playoff_config and playoff_config.status == "pending" and playoff_config.playoff_size > 0:
        if playoff_config.playoff_size == 32:
            required = 4
        else:
            required = int(math.log2(playoff_config.playoff_size))

        # Exclude the next upcoming tournament only when no league tournament is in
        # progress. While in progress, picks for the next tournament haven't opened
        # yet, so it remains eligible as a playoff round.
        has_in_progress = any(
            tournament_map[item.tournament_id].status == TournamentStatus.IN_PROGRESS.value
            for item in body.tournaments
            if tournament_map.get(item.tournament_id)
        )

        next_upcoming_id = None
        if not has_in_progress:
            next_upcoming = (
                db.query(Tournament)
                .filter(Tournament.status == TournamentStatus.SCHEDULED.value)
                .order_by(Tournament.start_date.asc())
                .first()
            )
            next_upcoming_id = next_upcoming.id if next_upcoming else None

        eligible = sum(
            1 for item in body.tournaments
            if tournament_map.get(item.tournament_id)
            and tournament_map[item.tournament_id].status == TournamentStatus.SCHEDULED.value
            and (next_upcoming_id is None or tournament_map[item.tournament_id].id != next_upcoming_id)
        )
        if eligible < required:
            raise HTTPException(
                status_code=422,
                detail=(
                    f"Schedule must include at least {required} future tournament(s) for the "
                    f"{playoff_config.playoff_size}-player playoff bracket (found {eligible})"
                ),
            )

    # Atomic replace: delete all existing selections, insert new ones.
    db.query(LeagueTournament).filter_by(league_id=league.id).delete()
    for item in body.tournaments:
        db.add(LeagueTournament(
            league_id=league.id,
            tournament_id=item.tournament_id,
            multiplier=item.multiplier,
        ))
    db.commit()

    # Re-score all completed tournament picks.
    # score_picks uses cached TournamentEntry.earnings_usd — no ESPN API calls.
    for item in body.tournaments:
        tournament = tournament_map.get(item.tournament_id)
        if tournament and tournament.status == TournamentStatus.COMPLETED.value:
            score_picks(db, tournament)

    rows = (
        db.query(LeagueTournament)
        .filter_by(league_id=league.id)
        .join(LeagueTournament.tournament)
        .order_by(Tournament.start_date.asc())
        .all()
    )
    playoff_ids = _playoff_tournament_ids_for_league(league.id, db)
    return [_build_league_tournament_out(row, db, playoff_ids) for row in rows]
